# Generated by Django 3.2.5 on 2021-09-10 13:00

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='News',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titolo', models.CharField(max_length=22)),
                ('data', models.DateTimeField(auto_now_add=True)),
                ('descrizione', models.TextField(blank=True, null=True)),
                ('img', models.ImageField(null=True, upload_to='images_uploaded', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['jpg', 'png', 'bmp'])])),
                ('video', models.FileField(null=True, upload_to='videos_uploaded', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['MOV', 'avi', 'mp4', 'webm', 'mkv'])])),
                ('user_nutrizionista', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='publisher', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Commenti',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.DateTimeField(auto_now_add=True)),
                ('titolo', models.CharField(max_length=22)),
                ('descrizione', models.TextField()),
                ('news', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='news.news')),
            ],
            options={
                'verbose_name': 'Commento',
                'verbose_name_plural': 'Commenti',
            },
        ),
    ]
