# Generated by Django 3.2.5 on 2021-09-10 13:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0003_auto_20210910_1521'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='news',
            options={'verbose_name': 'News', 'verbose_name_plural': 'News'},
        ),
        migrations.AddField(
            model_name='commenti',
            name='autore',
            field=models.CharField(blank=True, max_length=22, null=True),
        ),
    ]
