# Generated by Django 3.2.5 on 2021-08-27 11:42

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=22)),
                ('cognome', models.CharField(max_length=22)),
                ('numero_telefono', models.CharField(blank=True, max_length=22, null=True)),
                ('indirizzo', models.CharField(blank=True, max_length=50, null=True)),
                ('email', models.EmailField(blank=True, max_length=40, null=True)),
                ('patologia', models.TextField(blank=True, null=True)),
                ('user_cliente', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='nutrizionista', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Cliente',
                'verbose_name_plural': 'Clienti',
            },
        ),
        migrations.CreateModel(
            name='Visita',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.DateTimeField(auto_now_add=True)),
                ('argomento', models.CharField(max_length=22)),
                ('descrizione', models.TextField()),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cliente.cliente')),
            ],
            options={
                'verbose_name': 'Visita',
                'verbose_name_plural': 'Visite',
            },
        ),
    ]
