# Generated by Django 3.2.5 on 2021-08-27 11:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('cliente', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Giorno_settimana',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('giorno', models.CharField(max_length=10)),
            ],
            options={
                'verbose_name': 'Giorno della settimana',
                'verbose_name_plural': 'Giorni della settimana',
            },
        ),
        migrations.CreateModel(
            name='Ingrediente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Nome', models.CharField(max_length=22)),
                ('Flag_istamina', models.BooleanField(null=True)),
                ('Flag_nichel', models.BooleanField(null=True)),
                ('Flag_ferro', models.BooleanField(null=True)),
                ('Note', models.TextField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Ingrediente',
                'verbose_name_plural': 'Ingredienti',
            },
        ),
        migrations.CreateModel(
            name='Ingrediente_Piatto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Metodo_Preparazione', models.CharField(blank=True, max_length=22, null=True)),
                ('Quantità', models.FloatField()),
                ('UM', models.TextField(blank=True, max_length=5, null=True)),
                ('Nome', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dieta.ingrediente')),
            ],
            options={
                'verbose_name': 'Ingrediente nel piatto',
                'verbose_name_plural': 'Ingredienti nei piatti',
            },
        ),
        migrations.CreateModel(
            name='Piatto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_piatto', models.CharField(max_length=30)),
                ('costo_preparazione', models.IntegerField(blank=True, null=True)),
                ('categoria', models.IntegerField(blank=True, null=True)),
                ('descrizione', models.TextField(blank=True, null=True)),
                ('tempo_preparazione', models.IntegerField(blank=True, null=True)),
                ('tempo_cottura', models.IntegerField(blank=True, null=True)),
                ('ricetta', models.TextField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Piatto',
                'verbose_name_plural': 'Piatti',
            },
        ),
        migrations.CreateModel(
            name='Tipo_pasto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(max_length=10)),
            ],
            options={
                'verbose_name': 'Tipo di pasto',
                'verbose_name_plural': 'Tipi di pasto',
            },
        ),
        migrations.CreateModel(
            name='Piatti',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_piatto', models.CharField(max_length=30)),
                ('costo_preparazione', models.IntegerField(blank=True, null=True)),
                ('categoria', models.IntegerField(blank=True, null=True)),
                ('descrizione', models.TextField(blank=True, null=True)),
                ('tempo_preparazione', models.IntegerField(blank=True, null=True)),
                ('tempo_cottura', models.IntegerField(blank=True, null=True)),
                ('ricetta', models.TextField(blank=True, null=True)),
                ('Calorie_kcal', models.FloatField(blank=True, null=True)),
                ('Carboidrati_g', models.FloatField(blank=True, null=True)),
                ('Zuccheri_g', models.FloatField(blank=True, null=True)),
                ('Grassi_g', models.FloatField(blank=True, null=True)),
                ('Grassi_Saturi_g', models.FloatField(blank=True, null=True)),
                ('Fibre_g', models.FloatField(blank=True, null=True)),
                ('Colesterolo_m', models.FloatField(blank=True, null=True)),
                ('Sodio_mg', models.FloatField(blank=True, null=True)),
                ('ingredienti', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='dieta.ingrediente_piatto')),
            ],
            options={
                'verbose_name': 'Piatto',
                'verbose_name_plural': 'Piatti',
            },
        ),
        migrations.CreateModel(
            name='Dieta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.DateTimeField(auto_now_add=True, null=True)),
                ('nome_dieta', models.CharField(max_length=22)),
                ('descrizione', models.TextField(blank=True, null=True)),
                ('cliente_dieta', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='cliente.cliente')),
                ('giorno_settimana', models.ManyToManyField(to='dieta.Giorno_settimana')),
                ('nome_piatto', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='dieta.piatto')),
                ('tipo_pasto', models.ManyToManyField(to='dieta.Tipo_pasto')),
            ],
            options={
                'verbose_name': 'Dieta',
                'verbose_name_plural': 'Diete',
            },
        ),
    ]
