# Generated by Django 3.2.5 on 2021-08-27 12:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dieta', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='piatti',
            name='ingredienti',
        ),
        migrations.AddField(
            model_name='ingrediente_piatto',
            name='Piatto',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='dieta.piatti'),
        ),
    ]
