# Generated by Django 3.2.5 on 2021-08-27 14:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dieta', '0003_auto_20210827_1636'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='tipo_pasto_piatto',
            options={'verbose_name': 'Pasto vs Dieta', 'verbose_name_plural': 'Pasti vs Diete'},
        ),
        migrations.AlterField(
            model_name='tipo_pasto_piatto',
            name='nome_piatto',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dieta.piatti'),
        ),
        migrations.DeleteModel(
            name='Piatto',
        ),
    ]
