# Generated by Django 3.2.5 on 2021-09-10 13:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dieta', '0004_auto_20210827_1643'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tipo_pasto_piatto',
            name='tipo_pasto',
            field=models.ManyToManyField(to='dieta.Tipo_pasto'),
        ),
    ]
